module.exports = async (db) => {
  const questions = [
    {
      title: 'Two Sum',
      category: 'dsa',
      subcategory: 'Arrays Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/two-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Basics', ...["google","amazon","microsoft","meta","apple","netflix"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Remove Duplicates from Sorted Array',
      category: 'dsa',
      subcategory: 'Arrays Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/remove-duplicates-from-sorted-array\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Basics', ...["microsoft","amazon","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Remove Element',
      category: 'dsa',
      subcategory: 'Arrays Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/remove-element\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Basics', ...["microsoft","google"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Plus One',
      category: 'dsa',
      subcategory: 'Arrays Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/plus-one\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Basics', ...["google","amazon"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Majority Element',
      category: 'dsa',
      subcategory: 'Arrays Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/majority-element\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Basics', ...["amazon","microsoft","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'First Missing Positive',
      category: 'dsa',
      subcategory: 'Arrays Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/first-missing-positive\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Hard', ...["google","amazon","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Longest Consecutive Sequence',
      category: 'dsa',
      subcategory: 'Arrays Hard',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-consecutive-sequence\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Hard', ...["google","meta","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Find the Duplicate Number',
      category: 'dsa',
      subcategory: 'Arrays Hard',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-the-duplicate-number\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Hard', ...["amazon","apple","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Two Sum II - Input Array Is Sorted',
      category: 'dsa',
      subcategory: 'Arrays Two Pointers',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/two-sum-ii-input-array-is-sorted\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Two Pointers', ...["amazon","microsoft","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: '3Sum',
      category: 'dsa',
      subcategory: 'Arrays Two Pointers',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/3sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Two Pointers', ...["google","amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Container With Most Water',
      category: 'dsa',
      subcategory: 'Arrays Two Pointers',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/container-with-most-water\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Two Pointers', ...["amazon","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: '4Sum',
      category: 'dsa',
      subcategory: 'Arrays Two Pointers',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/4sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Two Pointers', ...["amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Substring Without Repeating Characters',
      category: 'dsa',
      subcategory: 'Arrays Sliding Window',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-substring-without-repeating-characters\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Sliding Window', ...["google","amazon","microsoft","meta","apple","netflix"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Find All Anagrams in a String',
      category: 'dsa',
      subcategory: 'Arrays Sliding Window',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-all-anagrams-in-a-string\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Sliding Window', ...["meta","google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Minimum Size Subarray Sum',
      category: 'dsa',
      subcategory: 'Arrays Sliding Window',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/minimum-size-subarray-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Sliding Window', ...["amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Minimum Window Substring',
      category: 'dsa',
      subcategory: 'Arrays Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/minimum-window-substring\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Hard', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Sliding Window Maximum',
      category: 'dsa',
      subcategory: 'Arrays Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/sliding-window-maximum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Arrays Hard', ...["google","amazon","netflix"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Valid Palindrome',
      category: 'dsa',
      subcategory: 'Strings Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/valid-palindrome\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Strings Basics', ...["microsoft","amazon","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Valid Anagram',
      category: 'dsa',
      subcategory: 'Strings Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/valid-anagram\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Strings Basics', ...["amazon","microsoft","google"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Longest Common Prefix',
      category: 'dsa',
      subcategory: 'Strings Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-common-prefix\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Strings Basics', ...["google","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Group Anagrams',
      category: 'dsa',
      subcategory: 'Strings Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/group-anagrams\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Strings Medium', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Palindromic Substring',
      category: 'dsa',
      subcategory: 'Strings Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-palindromic-substring\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Strings Medium', ...["amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Zigzag Conversion',
      category: 'dsa',
      subcategory: 'Strings Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/zigzag-conversion\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Strings Medium', ...["microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Regular Expression Matching',
      category: 'dsa',
      subcategory: 'DP Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/regular-expression-matching\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Hard', ...["google","microsoft","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Contains Duplicate',
      category: 'dsa',
      subcategory: 'Hashing',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/contains-duplicate\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Hashing', ...["google","amazon","microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Two Sum (Hash Map approach)',
      category: 'dsa',
      subcategory: 'Hashing',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/two-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Hashing', ...["meta","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Top K Frequent Elements',
      category: 'dsa',
      subcategory: 'Hashing',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/top-k-frequent-elements\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Hashing', ...["amazon","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Group Anagrams (Hashing focus)',
      category: 'dsa',
      subcategory: 'Hashing',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/group-anagrams\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Hashing', ...["microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'First Unique Character in a String',
      category: 'dsa',
      subcategory: 'Hashing',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/first-unique-character-in-a-string\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Hashing', ...["amazon","microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Product of Array Except Self',
      category: 'dsa',
      subcategory: 'Prefix Sum',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/product-of-array-except-self\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Prefix Sum', ...["amazon","meta","google","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Subarray Sum Equals K',
      category: 'dsa',
      subcategory: 'Prefix Sum',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/subarray-sum-equals-k\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Prefix Sum', ...["google","amazon","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Range Sum Query - Immutable',
      category: 'dsa',
      subcategory: 'Prefix Sum',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/range-sum-query-immutable\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Prefix Sum', ...["microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Range Sum Query 2D - Immutable',
      category: 'dsa',
      subcategory: 'Prefix Sum',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/range-sum-query-2d-immutable\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Prefix Sum', ...["google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Binary Search',
      category: 'dsa',
      subcategory: 'Binary Search',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/binary-search\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Search Insert Position',
      category: 'dsa',
      subcategory: 'Binary Search',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/search-insert-position\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search', ...["amazon","microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Search in Rotated Sorted Array',
      category: 'dsa',
      subcategory: 'Binary Search',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/search-in-rotated-sorted-array\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search', ...["amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Find Minimum in Rotated Sorted Array',
      category: 'dsa',
      subcategory: 'Binary Search',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Median of Two Sorted Arrays',
      category: 'dsa',
      subcategory: 'Binary Search Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/median-of-two-sorted-arrays\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search Hard', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Find Minimum in Rotated Sorted Array II',
      category: 'dsa',
      subcategory: 'Binary Search Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search Hard', ...["google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Split Array Largest Sum',
      category: 'dsa',
      subcategory: 'Binary Search Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/split-array-largest-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Binary Search Hard', ...["amazon","google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Climbing Stairs',
      category: 'dsa',
      subcategory: 'Recursion',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/climbing-stairs\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Recursion', ...["amazon","microsoft","google"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Fibonacci Number',
      category: 'dsa',
      subcategory: 'Recursion',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/fibonacci-number\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Recursion', ...["amazon"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Pow(x, n)',
      category: 'dsa',
      subcategory: 'Recursion',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/powx-n\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Recursion', ...["google","amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Reverse Linked List',
      category: 'dsa',
      subcategory: 'Linked List Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/reverse-linked-list\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Basics', ...["google","amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Merge Two Sorted Lists',
      category: 'dsa',
      subcategory: 'Linked List Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-two-sorted-lists\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Basics', ...["amazon","microsoft","google","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Remove Duplicates from Sorted List',
      category: 'dsa',
      subcategory: 'Linked List Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/remove-duplicates-from-sorted-list\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Basics', ...["microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Linked List Cycle',
      category: 'dsa',
      subcategory: 'Linked List Medium',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked-list-cycle\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Medium', ...["amazon","microsoft","google"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Remove Nth Node From End of List',
      category: 'dsa',
      subcategory: 'Linked List Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/remove-nth-node-from-end-of-list\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Medium', ...["amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Linked List Cycle II',
      category: 'dsa',
      subcategory: 'Linked List Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked-list-cycle-ii\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Medium', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Copy List with Random Pointer',
      category: 'dsa',
      subcategory: 'Linked List Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/copy-list-with-random-pointer\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Medium', ...["meta","amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Merge K Sorted Lists',
      category: 'dsa',
      subcategory: 'Linked List Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-k-sorted-lists\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Hard', ...["google","amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Reverse Nodes in k-Group',
      category: 'dsa',
      subcategory: 'Linked List Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/reverse-nodes-in-k-group\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Linked List Hard', ...["microsoft","amazon","google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Valid Parentheses',
      category: 'dsa',
      subcategory: 'Stacks',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/valid-parentheses\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Min Stack',
      category: 'dsa',
      subcategory: 'Stacks',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/min-stack\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Evaluate Reverse Polish Notation',
      category: 'dsa',
      subcategory: 'Stacks',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/evaluate-reverse-polish-notation\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks', ...["amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Daily Temperatures',
      category: 'dsa',
      subcategory: 'Stacks',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/daily-temperatures\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks', ...["amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Trapping Rain Water',
      category: 'dsa',
      subcategory: 'Stacks Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trapping-rain-water\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks Hard', ...["google","amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Largest Rectangle in Histogram',
      category: 'dsa',
      subcategory: 'Stacks Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/largest-rectangle-in-histogram\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks Hard', ...["google","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Longest Valid Parentheses',
      category: 'dsa',
      subcategory: 'Stacks Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-valid-parentheses\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Stacks Hard', ...["google","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Implement Stack using Queues',
      category: 'dsa',
      subcategory: 'Queues',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/implement-stack-using-queues\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Queues', ...["amazon","microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Design Circular Queue',
      category: 'dsa',
      subcategory: 'Queues',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/design-circular-queue\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Queues', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Implement Queue using Stacks',
      category: 'dsa',
      subcategory: 'Queues',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/implement-queue-using-stacks\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Queues', ...["microsoft","amazon"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Maximum Depth of Binary Tree',
      category: 'dsa',
      subcategory: 'Trees Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/maximum-depth-of-binary-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Basics', ...["google","amazon","microsoft","meta","apple"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Invert Binary Tree',
      category: 'dsa',
      subcategory: 'Trees Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/invert-binary-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Basics', ...["google","amazon"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Same Tree',
      category: 'dsa',
      subcategory: 'Trees Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/same-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Basics', ...["amazon","microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Diameter of Binary Tree',
      category: 'dsa',
      subcategory: 'Trees Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/diameter-of-binary-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Basics', ...["microsoft","meta"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Binary Tree Level Order Traversal',
      category: 'dsa',
      subcategory: 'Trees Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/binary-tree-level-order-traversal\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Medium', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Lowest Common Ancestor of a Binary Tree',
      category: 'dsa',
      subcategory: 'Trees Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Medium', ...["google","amazon","meta","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Construct Binary Tree from Preorder and Inorder Traversal',
      category: 'dsa',
      subcategory: 'Trees Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Medium', ...["amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Binary Tree Maximum Path Sum',
      category: 'dsa',
      subcategory: 'Trees Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/binary-tree-maximum-path-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Hard', ...["google","amazon","meta","microsoft"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Serialize and Deserialize Binary Tree',
      category: 'dsa',
      subcategory: 'Trees Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/serialize-and-deserialize-binary-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Hard', ...["google","meta","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Vertical Order Traversal of a Binary Tree',
      category: 'dsa',
      subcategory: 'Trees Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Trees Hard', ...["amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Search in a Binary Search Tree',
      category: 'dsa',
      subcategory: 'BST',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/search-in-a-binary-search-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['BST', ...["amazon","microsoft"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Validate Binary Search Tree',
      category: 'dsa',
      subcategory: 'BST',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/validate-binary-search-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['BST', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Kth Smallest Element in a BST',
      category: 'dsa',
      subcategory: 'BST',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/kth-smallest-element-in-a-bst\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['BST', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Delete Node in a BST',
      category: 'dsa',
      subcategory: 'BST',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/delete-node-in-a-bst\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['BST', ...["microsoft","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Kth Largest Element in a Stream',
      category: 'dsa',
      subcategory: 'Heaps',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/kth-largest-element-in-a-stream\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Heaps', ...["amazon","google"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Kth Largest Element in an Array',
      category: 'dsa',
      subcategory: 'Heaps',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/kth-largest-element-in-an-array\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Heaps', ...["amazon","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'K Closest Points to Origin',
      category: 'dsa',
      subcategory: 'Heaps',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/k-closest-points-to-origin\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Heaps', ...["amazon","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Merge K Sorted Lists (Heap focus)',
      category: 'dsa',
      subcategory: 'Heaps Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-k-sorted-lists\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Heaps Hard', ...["google","amazon","netflix"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Find Median from Data Stream',
      category: 'dsa',
      subcategory: 'Heaps Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-median-from-data-stream\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Heaps Hard', ...["google","amazon","microsoft","netflix"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'IPO',
      category: 'dsa',
      subcategory: 'Heaps Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/ipo\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Heaps Hard', ...["amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Merge Sorted Array',
      category: 'dsa',
      subcategory: 'Sorting',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-sorted-array\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Sorting', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Merge Intervals',
      category: 'dsa',
      subcategory: 'Sorting',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-intervals\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Sorting', ...["google","meta","amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Largest Number',
      category: 'dsa',
      subcategory: 'Sorting',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/largest-number\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Sorting', ...["amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Sort Colors',
      category: 'dsa',
      subcategory: 'Sorting',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/sort-colors\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Sorting', ...["microsoft","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Insert Interval',
      category: 'dsa',
      subcategory: 'Sorting Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/insert-interval\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Sorting Hard', ...["google","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Insert Interval',
      category: 'dsa',
      subcategory: 'Intervals',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/insert-interval\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Intervals', ...["google","meta","amazon","apple"]]),
      time_limit_seconds: 2400
    },
    {
      title: 'Minimum Number of Arrows to Burst Balloons',
      category: 'dsa',
      subcategory: 'Intervals',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N log N), Space: O(1)',
      tags: JSON.stringify(['Intervals', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 2400
    },
    {
      title: 'Permutations',
      category: 'dsa',
      subcategory: 'Backtracking',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/permutations\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking', ...["amazon","microsoft","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Subsets',
      category: 'dsa',
      subcategory: 'Backtracking',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/subsets\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking', ...["amazon","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Combination Sum',
      category: 'dsa',
      subcategory: 'Backtracking',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/combination-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking', ...["amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Word Search',
      category: 'dsa',
      subcategory: 'Backtracking',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/word-search\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking', ...["amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'N-Queens',
      category: 'dsa',
      subcategory: 'Backtracking Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/n-queens\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking Hard', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Sudoku Solver',
      category: 'dsa',
      subcategory: 'Backtracking Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/sudoku-solver\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking Hard', ...["google","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Word Search II',
      category: 'dsa',
      subcategory: 'Backtracking Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/word-search-ii\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Backtracking Hard', ...["google","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Number of Islands',
      category: 'dsa',
      subcategory: 'Graphs BFS/DFS',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/number-of-islands\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs BFS/DFS', ...["google","amazon","microsoft","meta","apple","netflix"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Clone Graph',
      category: 'dsa',
      subcategory: 'Graphs BFS/DFS',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/clone-graph\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs BFS/DFS', ...["google","amazon","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Surrounded Regions',
      category: 'dsa',
      subcategory: 'Graphs BFS/DFS',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/surrounded-regions\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs BFS/DFS', ...["amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Course Schedule',
      category: 'dsa',
      subcategory: 'Graphs Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/course-schedule\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs Medium', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Pacific Atlantic Water Flow',
      category: 'dsa',
      subcategory: 'Graphs Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/pacific-atlantic-water-flow\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs Medium', ...["amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Rotting Oranges',
      category: 'dsa',
      subcategory: 'Graphs Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/rotting-oranges\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs Medium', ...["amazon","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Course Schedule II',
      category: 'dsa',
      subcategory: 'Tries',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/course-schedule-ii\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(V + E), Space: O(V + E)',
      tags: JSON.stringify(['Graphs', ...["meta","amazon","google","microsoft"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Longest Increasing Path in a Matrix',
      category: 'dsa',
      subcategory: 'Graphs Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-increasing-path-in-a-matrix\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs Hard', ...["google","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Swim in Rising Water',
      category: 'dsa',
      subcategory: 'Graphs Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/swim-in-rising-water\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Graphs Hard', ...["google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Network Delay Time',
      category: 'dsa',
      subcategory: 'Dijkstra',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/network-delay-time\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Dijkstra', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Cheapest Flights Within K Stops',
      category: 'dsa',
      subcategory: 'Dijkstra',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/cheapest-flights-within-k-stops\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Dijkstra', ...["amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Path With Minimum Effort',
      category: 'dsa',
      subcategory: 'Dijkstra',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/path-with-minimum-effort\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Dijkstra', ...["google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'House Robber',
      category: 'dsa',
      subcategory: 'DP Basics',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/house-robber\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Basics', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Coin Change',
      category: 'dsa',
      subcategory: 'DP Basics',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/coin-change\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Basics', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Climbing Stairs (DP focus)',
      category: 'dsa',
      subcategory: 'DP Basics',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/climbing-stairs\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Basics', ...["meta"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Longest Increasing Subsequence',
      category: 'dsa',
      subcategory: 'DP Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-increasing-subsequence\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Medium', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Common Subsequence',
      category: 'dsa',
      subcategory: 'DP Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-common-subsequence\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Medium', ...["amazon","google","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Word Break',
      category: 'dsa',
      subcategory: 'DP Medium',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/word-break\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Medium', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Unique Paths',
      category: 'dsa',
      subcategory: 'DP 2D',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/unique-paths\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP 2D', ...["amazon","google","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Minimum Path Sum',
      category: 'dsa',
      subcategory: 'DP 2D',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/minimum-path-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP 2D', ...["amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Best Time to Buy and Sell Stock',
      category: 'dsa',
      subcategory: 'DP 2D',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/best-time-to-buy-and-sell-stock\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP 2D', ...["google","amazon","microsoft","meta","netflix"]]),
      time_limit_seconds: 1800
    },
    {
      title: 'Edit Distance',
      category: 'dsa',
      subcategory: 'DP Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/edit-distance\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Hard', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Burst Balloons',
      category: 'dsa',
      subcategory: 'DP Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/burst-balloons\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Hard', ...["google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Wildcard Matching',
      category: 'dsa',
      subcategory: 'DP Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/wildcard-matching\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['DP Hard', ...["meta","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Jump Game',
      category: 'dsa',
      subcategory: 'Greedy',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/jump-game\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Greedy', ...["google","amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Jump Game II',
      category: 'dsa',
      subcategory: 'Greedy',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/jump-game-ii\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Greedy', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Gas Station',
      category: 'dsa',
      subcategory: 'Greedy',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/gas-station\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Greedy', ...["amazon","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Candy',
      category: 'dsa',
      subcategory: 'Greedy Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/candy\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Greedy Hard', ...["google","amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'IPO (Greedy focus)',
      category: 'dsa',
      subcategory: 'Greedy Hard',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/ipo\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Greedy Hard', ...["amazon"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Partition Labels',
      category: 'dsa',
      subcategory: 'Greedy Hard',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/partition-labels\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Greedy Hard', ...["amazon","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'LRU Cache',
      category: 'dsa',
      subcategory: 'Design',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/lru-cache\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Design', ...["google","amazon","microsoft","meta","apple","netflix"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Min Stack (Design focus)',
      category: 'dsa',
      subcategory: 'Design',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/min-stack\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Design', ...["amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Implement Trie (Prefix Tree)',
      category: 'dsa',
      subcategory: 'Tries',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/implement-trie-prefix-tree\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Tries', ...["google","amazon","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Design Add and Search Words Data Structure',
      category: 'dsa',
      subcategory: 'Tries',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/design-add-and-search-words-data-structure\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Tries', ...["amazon","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Word Search II (Trie focus)',
      category: 'dsa',
      subcategory: 'Tries',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/word-search-ii\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Tries', ...["google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Range Sum Query - Mutable',
      category: 'dsa',
      subcategory: 'Segment Tree',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/range-sum-query-mutable\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Segment Tree', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Count of Smaller Numbers After Self',
      category: 'dsa',
      subcategory: 'Segment Tree',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/count-of-smaller-numbers-after-self\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Segment Tree', ...["google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Count of Range Sum',
      category: 'dsa',
      subcategory: 'Segment Tree',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/count-of-range-sum\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Segment Tree', ...["google"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Maximum Subarray',
      category: 'dsa',
      subcategory: 'Mock Test',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/maximum-subarray\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Mock Test', ...["google","amazon","microsoft","apple","netflix"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Rotate Image',
      category: 'dsa',
      subcategory: 'Mock Test',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/rotate-image\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Mock Test', ...["amazon","microsoft","meta"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Spiral Matrix',
      category: 'dsa',
      subcategory: 'Mock Test 2',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/spiral-matrix\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Mock Test 2', ...["amazon","microsoft","meta","google"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'K Closest Points to Origin (Mock)',
      category: 'dsa',
      subcategory: 'Mock Test 2',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/k-closest-points-to-origin\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Mock Test 2', ...["amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Number of Islands (Revision)',
      category: 'dsa',
      subcategory: 'Revision',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/number-of-islands\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Revision', ...["google","amazon"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Merge Intervals (Revision)',
      category: 'dsa',
      subcategory: 'Revision',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-intervals\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Revision', ...["meta","microsoft"]]),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Valid Parentheses (Final)',
      category: 'dsa',
      subcategory: 'Final Mock',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-valid-parentheses\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Final Mock', ...["google","meta"]]),
      time_limit_seconds: 3600
    },
    {
      title: 'Remove Invalid Parentheses (Final)',
      category: 'dsa',
      subcategory: 'Final Mock',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/remove-invalid-parentheses\n',
      correct_answer: 'Apply standard algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['Final Mock', ...["meta","google","amazon"]]),
      time_limit_seconds: 3600
    }
  ];

  await db.Question.bulkCreate(questions);
  console.log('✅ ' + questions.length + ' DSA Questions Seeded');
};
