module.exports = async (db) => {
  const questions = [
    {
      title: 'Two Sum',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/two-sum\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Best Time to Buy and Sell Stock',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/best-time-to-buy-and-sell-stock\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Contains Duplicate',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/contains-duplicate\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Product of Array Except Self',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/product-of-array-except-self\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Maximum Subarray',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/maximum-subarray\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Maximum Product Subarray',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/maximum-product-subarray\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Find Minimum in Rotated Sorted Array',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-minimum-in-rotated-sorted-array\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Search in Rotated Sorted Array',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/search-in-rotated-sorted-array\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: '3Sum',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/3sum\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Container With Most Water',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/container-with-most-water\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Merge Intervals',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-intervals\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Insert Interval',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/insert-interval\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Sort Colors',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/sort-colors\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Find All Numbers Disappeared in an Array',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/find-all-numbers-disappeared-in-an-array\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Move Zeroes',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/move-zeroes\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Valid Palindrome',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/valid-palindrome\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Valid Anagram',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/valid-anagram\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Valid Parentheses',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/valid-parentheses\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Longest Substring Without Repeating Characters',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-substring-without-repeating-characters\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Palindromic Substring',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-palindromic-substring\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Palindromic Substrings',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/palindromic-substrings\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Group Anagrams',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/group-anagrams\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Repeating Character Replacement',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-repeating-character-replacement\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Minimum Window Substring',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/minimum-window-substring\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 3600
    },
    {
      title: 'Implement strStr()',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/implement-strstr\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Reverse Linked List',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/reverse-linked-list\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Linked List Cycle',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked-list-cycle\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Merge Two Sorted Lists',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-two-sorted-lists\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Remove Nth Node From End of List',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/remove-nth-node-from-end-of-list\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Reorder List',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/reorder-list\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Copy List with Random Pointer',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/copy-list-with-random-pointer\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Add Two Numbers',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/add-two-numbers\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Intersection of Two Linked Lists',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/intersection-of-two-linked-lists\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Palindrome Linked List',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/palindrome-linked-list\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Merge k Sorted Lists',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/merge-k-sorted-lists\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 3600
    },
    {
      title: 'Maximum Depth of Binary Tree',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/maximum-depth-of-binary-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Same Tree',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/same-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Invert Binary Tree',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/invert-binary-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Binary Tree Maximum Path Sum',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/binary-tree-maximum-path-sum\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 3600
    },
    {
      title: 'Binary Tree Level Order Traversal',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/binary-tree-level-order-traversal\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Serialize and Deserialize Binary Tree',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/serialize-and-deserialize-binary-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 3600
    },
    {
      title: 'Subtree of Another Tree',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/subtree-of-another-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Construct Binary Tree from Preorder and Inorder Traversal',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Validate Binary Search Tree',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/validate-binary-search-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Kth Smallest Element in a BST',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/kth-smallest-element-in-a-bst\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Lowest Common Ancestor of a BST',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Implement Trie (Prefix Tree)',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/implement-trie-prefix-tree\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Design Add and Search Words Data Structure',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/design-add-and-search-words-data-structure\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Number of Islands',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/number-of-islands\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Clone Graph',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/clone-graph\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Pacific Atlantic Water Flow',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/pacific-atlantic-water-flow\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Course Schedule',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/course-schedule\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Course Schedule II',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/course-schedule-ii\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Alien Dictionary',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/alien-dictionary\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 3600
    },
    {
      title: 'Graph Valid Tree',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graph-valid-tree\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Number of Connected Components in an Undirected Graph',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Word Ladder',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/word-ladder\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 3600
    },
    {
      title: 'Climbing Stairs',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/climbing-stairs\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 1800
    },
    {
      title: 'Coin Change',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/coin-change\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Increasing Subsequence',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-increasing-subsequence\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Longest Common Subsequence',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/longest-common-subsequence\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Word Break',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/word-break\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Combination Sum',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/combination-sum\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'House Robber',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/house-robber\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'House Robber II',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/house-robber-ii\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Decode Ways',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/decode-ways\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Unique Paths',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/unique-paths\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Jump Game',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/jump-game\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard arrays Problem 69',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/arrays-problem-69\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard arrays Problem 70',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/arrays-problem-70\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard arrays Problem 71',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/arrays-problem-71\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard arrays Problem 72',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/arrays-problem-72\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard arrays Problem 73',
      category: 'dsa',
      subcategory: 'arrays',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/arrays-problem-73\n',
      correct_answer: 'Apply standard arrays algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['arrays']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard strings Problem 74',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-74\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard strings Problem 75',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-75\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard strings Problem 76',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-76\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard strings Problem 77',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-77\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard strings Problem 78',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-78\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard strings Problem 79',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-79\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard strings Problem 80',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-80\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard strings Problem 81',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-81\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard strings Problem 82',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-82\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard strings Problem 83',
      category: 'dsa',
      subcategory: 'strings',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/strings-problem-83\n',
      correct_answer: 'Apply standard strings algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['strings']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard linked_list Problem 84',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-84\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard linked_list Problem 85',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-85\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard linked_list Problem 86',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-86\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard linked_list Problem 87',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-87\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard linked_list Problem 88',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-88\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard linked_list Problem 89',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-89\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard linked_list Problem 90',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-90\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard linked_list Problem 91',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-91\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard linked_list Problem 92',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-92\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard linked_list Problem 93',
      category: 'dsa',
      subcategory: 'linked_list',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/linked_list-problem-93\n',
      correct_answer: 'Apply standard linked_list algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['linked_list']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard trees Problem 94',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-94\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard trees Problem 95',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-95\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard trees Problem 96',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-96\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard trees Problem 97',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-97\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard trees Problem 98',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-98\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard trees Problem 99',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-99\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard trees Problem 100',
      category: 'dsa',
      subcategory: 'trees',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/trees-problem-100\n',
      correct_answer: 'Apply standard trees algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['trees']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard graphs Problem 101',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-101\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard graphs Problem 102',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-102\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard graphs Problem 103',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-103\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard graphs Problem 104',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-104\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard graphs Problem 105',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-105\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard graphs Problem 106',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-106\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard graphs Problem 107',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-107\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard graphs Problem 108',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-108\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard graphs Problem 109',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-109\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard graphs Problem 110',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-110\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard graphs Problem 111',
      category: 'dsa',
      subcategory: 'graphs',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/graphs-problem-111\n',
      correct_answer: 'Apply standard graphs algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['graphs']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard dynamic_programming Problem 112',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-112\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard dynamic_programming Problem 113',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-113\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard dynamic_programming Problem 114',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-114\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard dynamic_programming Problem 115',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-115\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard dynamic_programming Problem 116',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-116\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard dynamic_programming Problem 117',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-117\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 3600
    },
    {
      title: 'Standard dynamic_programming Problem 118',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'medium',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-118\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 2700
    },
    {
      title: 'Standard dynamic_programming Problem 119',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'easy',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-119\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 1800
    },
    {
      title: 'Standard dynamic_programming Problem 120',
      category: 'dsa',
      subcategory: 'dynamic_programming',
      difficulty: 'hard',
      description: 'Loading description from LeetCode...\n\nLeetCode: https://leetcode.com/problems/dynamic_programming-problem-120\n',
      correct_answer: 'Apply standard dynamic_programming algorithm.',
      explanation: 'Time Complexity: O(N), Space: O(N)',
      tags: JSON.stringify(['dynamic_programming']),
      time_limit_seconds: 3600
    }
  ];

  await db.Question.bulkCreate(questions);
  console.log(`✅ ${questions.length} DSA Questions Seeded`);
};
